server:
  port: 9999

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///cainiao
  redis:
    port: 6379
    host: localhost

logging:
  level:
    com.it: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1 # 逻辑已删除
      logic-not-delete-value: 0 # 逻辑未删除

  type-aliases-package: com.it.*.entity
